services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simulations_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 10s
      retries: 5

  api:
    build: ./api
    ports:
      - "3002:3002"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: simulations_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build: ./worker
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: simulations_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  web:
    build: ./web
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE: http://localhost:3002
    depends_on:
      - api